name: Build - Linux

on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ["18.5.0"]
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com/"
          scope: "@luxonis"
      - name: Prepare Cross Compile
        run: |
          sudo apt update
          sudo apt install -y g++-aarch64-linux-gnu gcc-aarch64-linux-gnu crossbuild-essential-arm64
          mkdir sysroot && cd sysroot
          wget https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/953c2471bc7e71a788309f6c2d2003e8b703305d/debian_sid_arm64_sysroot.tar.xz        
          tar xf debian_sid_arm64_sysroot.tar.xz
          echo "ARM64_SYSROOT=$(pwd)" >> $GITHUB_ENV
          ls -l
      - name: Build
        run: |
          npm install
          npm run clean
          npm run prepare-prebuilds:amd64
          npm run clean
          npm run prepare-prebuilds:arm64
        env:
          CI: true
      - name: Test
        run: |
          npm install
          npm run test
        env:
          CI: true
      - name: Publish
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
